sudo: required

language: python
python:
  - 2.7

services:
  - docker

install:
  - docker-compose build
  - docker-compose start

after_success:
  - docker --version
  - docker-compose --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region us-east-1)
  - docker-compose build
  - docker tag nginxpy2:latest [your_ecr_account].dkr.ecr.us-east-1.amazonaws.com/nginxpy2:latest
  - docker tag couchdb:latest [your_ecr_account].dkr.ecr.us-east-1.amazonaws.com/couchdb:latest
  - docker tag data:latest [your_ecr_account].dkr.ecr.us-east-1.amazonaws.com/data:latest
  - docker push [your_ecr_account].dkr.ecr.us-east-1.amazonaws.com/nginxpy2:latest
  - docker push [your_ecr_account].dkr.ecr.us-east-1.amazonaws.com/couchdb:latest
  - docker push [your_ecr_account].dkr.ecr.us-east-1.amazonaws.com/data:latest
