sudo: required

language: python
python:
  - 2.7

services:
  - docker

install:
  - docker-compose build
  - docker-compose start

before_script:
    #install any requirements for tests here

script:
    #run tests here

after_success:
  - docker --version
  - docker-compose --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region us-east-1)
  - docker-compose build
  - docker tag data:latest [your_ecr_account].dkr.ecr.us-east-1.amazonaws.com/data:latest
  - docker tag db:latest [your_ecr_account].dkr.ecr.us-east-1.amazonaws.com/db:latest
  - docker tag app:latest [your_ecr_account].dkr.ecr.us-east-1.amazonaws.com/app:latest
  - docker tag webserver:latest [your_ecr_account].dkr.ecr.us-east-1.amazonaws.com/webserver:latest
  - docker push [your_ecr_account].dkr.ecr.us-east-1.amazonaws.com/data:latest
  - docker push [your_ecr_account].dkr.ecr.us-east-1.amazonaws.com/db:latest
  - docker push [your_ecr_account].dkr.ecr.us-east-1.amazonaws.com/app:latest
  - docker push [your_ecr_account].dkr.ecr.us-east-1.amazonaws.com/webserver:latest