version: "2"
services:
    couchdb:
        image: couchdb:3.4.2
        container_name: couchdb
        ports:
            - "5984:5984"
        volumes_from:
            - data
        depends_on:
            - data
        env_file:
            - ./config.env

    nginxpy2:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nginxpy2
        volumes:
            - ./django/app:/var/www/
            - /var/www/app/app/static-files
        expose:
            - "8000"
        depends_on:
            - couchdb
        env_file:
            - ./config.env
    data:
      image: gliderlabs/alpine:3.3
      container_name: data
      volumes:
        - /usr/local/var/lib/couchdb