version: "2"
services:
    db:
        image: couchdb:1.6.1
        container_name: db
        ports:
            - "5984:5984"
        volumes_from:
            - data
        depends_on:
            - data
        env_file:
            - ./config.env

    webserver:
        build:
            context: .
            dockerfile: nginx/Dockerfile
        container_name: webserver
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - app
        volumes_from:
            - app
        env_file:
            - ./config.env

    app:
        build:
            context: .
            dockerfile: django/Dockerfile
        container_name: app
        volumes:
            - ./django/app:/var/www/
            - /var/www/app/app/static-files
        expose:
            - "8000"
        depends_on:
            - db
        env_file:
            - ./config.env
    data:
      image: gliderlabs/alpine:3.3
      container_name: data
      volumes:
        - /usr/local/var/lib/couchdb