version: "2"
services:
  nginxpy2:
  	image: padrian/nginxpy2
    depends_on: 
      - couchdb
    container_name: nginxpy2
    env_file:
      - ./config.env

  data:
    image: gliderlabs/alpine:3.9
    container_name: data
    volumes:
      - /usr/local/var/lib/couchdb
    env_file:
      - ./config.env


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginxpy2
    expose:
      - "8000"
    depends_on:
      - couchdb

  couchdb:
  	image: couchdb
  	ports:
  		- "5984:5984"
    env_file:
      - ./config.env      
    depends_on:
      - data  